#!/bin/zsh

zmodload zsh/zutil

function mux() {
    local -a arg_instance arg_background
    zparseopts -D -- \
        {b,-background}=arg_background \
        {I,-instance}:=arg_instance ||
    return

    local instance
    if [[ -n $arg_instance ]]; then
        instance="$arg_instance[-1]"
    elif [[ -n "$MUX_SOCKET" ]]; then
        instance="$MUX_SOCKET"
    else
        echo '$MUX_SOCKET is not set' >&2
        return 1
    fi

    if [[ -z $arg_background ]]; then
        command-server-call "$instance" "$@"
    else
        command-server-call-and-forget "$instance" "$@"
    fi
}

mux "$@"
